### ISSUE TITLE
NeosPluginManager.dll no longer exists

### ISSUE THREAD

**Issue by RobertBaruch** [Aerizeon/NeosWikiAssetGenerator#2]
In the launch settings:

`-LoadAssembly` "Libraries\PluginManager\NeosPluginManager.dll"`

This library is no longer present, so this option can be removed.

**Comment by Aerizeon** [comment]
Removed from launch settings in 4bf69f8c9d289eebf23e21bbb9d91827200a2ded 

This was leftover from when I was working on another project concurrently, and was no longer needed

Thanks!
