### ISSUE TITLE
Retarget project to .NET Framework 4.6.2

### ISSUE THREAD

**Issue by XekriRedmane** [Aerizeon/NeosWikiAssetGenerator#6]
Apparently the project currently targets .NET Standard 2.0, but that leads to conflicts in System.Net.Http (Neos uses v4.2, which isn't available for Standard 2.0), System.IO.Compress (same) and System.ValueTuple (Neos uses v4.0.3, which also isn't available).

The solution is to target .NET Framework 4.6.2.

Examination of the plugins included with Neos (via JustDecompiler) show that they were all targeted to .NET Framework 4.6.2.

**Comment by Aerizeon** [comment]
Fixed in 4bf69f8c9d289eebf23e21bbb9d91827200a2ded

I think I accidentally set it to Netstandard while working on something else, oops!

Thank you!
